const userFunctions = [
  { name: "add_user_exp", args: "p_user_id uuid, p_amount integer, p_reason text, p_type text" },
  { name: "add_user_exp", args: "p_user_id uuid, p_amount integer, p_reason text, p_type text, p_target_id text DEFAULT NULL::text" },
  { name: "add_user_points", args: "p_user_id uuid, p_amount integer, p_reason text, p_type text, p_target_id text DEFAULT NULL::text" },
  { name: "add_user_points", args: "p_user_id uuid, p_amount integer, p_reason text, p_type text" },
  { name: "add_virtual_views", args: "item_id uuid, amount integer" },
  { name: "adjust_heat", args: "p_item_id uuid, p_amount double precision" },
  { name: "approve_staging_items", args: "p_ids uuid[]" },
  { name: "archive_all_approved_media", args: "" },
  { name: "auto_refill_pending_daily_gallery_materials", args: "" },
  { name: "auto_tag_media_logic", args: "" },
  { name: "award_user_reward", args: "p_user_id uuid, p_action text, p_target_id text DEFAULT NULL::text" },
  { name: "batch_hard_delete_media", args: "p_ids uuid[]" },
  { name: "batch_insert_zonerama_photos", args: "p_album_id text, p_photos jsonb" },
  { name: "batch_restore_media", args: "p_ids uuid[]" },
  { name: "batch_soft_delete_media", args: "p_ids uuid[]" },
  { name: "batch_update_media_hashes", args: "p_updates jsonb" },
  { name: "batch_update_media_status_rpc", args: "p_ids uuid[], p_status text, p_reason text DEFAULT NULL::text" },
  { name: "bulk_ignore_dedupe", args: "p_ids uuid[]" },
  { name: "buy_special_id", args: "p_user_id uuid, p_special_id uuid" },
  { name: "check_album_photo_similar", args: "p_album_id uuid, p_hash text, p_threshold integer DEFAULT 5" },
  { name: "check_user_favorites", args: "p_user_id uuid, p_media_ids uuid[]" },
  { name: "check_user_sessions_by_identifier", args: "p_identifier text" },
  { name: "cleanup_expired_invitations", args: "" },
  { name: "cleanup_old_notifications", args: "days_threshold integer" },
  { name: "cleanup_old_web_vitals", args: "" },
  { name: "clear_all_duplicate_media", args: "" },
  { name: "clear_all_visual_duplicates", args: "p_threshold integer DEFAULT 5" },
  { name: "clear_dedupe_errors", args: "p_table text DEFAULT 'media_items'::text" },
  { name: "create_notification", args: "p_user_id uuid, p_type text, p_title text, p_content text, p_link text DEFAULT NULL::text" },
  { name: "create_or_merge_audit_notification", args: "user_id uuid, media_id uuid, media_title text, status text, reason text DEFAULT NULL::text" },
  { name: "crypt", args: "text, text" },
  { name: "delete_media_with_thumbnail", args: "" },
  { name: "exec_sql", args: "query_text text" },
  { name: "execute_admin_sql", args: "sql_query text" },
  { name: "find_duplicate_media", args: "p_file_hash text, p_user_id uuid DEFAULT NULL::uuid" },
  { name: "find_similar_media", args: "target_hash text, threshold integer DEFAULT 5" },
  { name: "flush_notification_buffer", args: "" },
  { name: "gen_salt", args: "text" },
  { name: "generate_digital_id", args: "" },
  { name: "get_admin_analytics", args: "" },
  { name: "get_admin_distribution", args: "" },
  { name: "get_admin_stats", args: "" },
  { name: "get_album_photo_level_counts", args: "p_album_id uuid" },
  { name: "get_cache_hit_rate", args: "p_cache_key text" },
  { name: "get_category_cloud", args: "" },
  { name: "get_daily_gallery_available_images_rpc", args: "p_limit integer, p_offset integer, p_search text DEFAULT NULL::text, p_status text DEFAULT 'unused'::text" },
  { name: "get_daily_gallery_stats", args: "p_start_date date DEFAULT NULL::date, p_end_date date DEFAULT NULL::date" },
  { name: "get_database_stats", args: "" },
  { name: "get_database_table_stats", args: "" },
  { name: "get_dedupe_stats", args: "" },
  { name: "get_duplicate_media", args: "" },
  { name: "get_fast_organize_pending", args: "p_user_id uuid, p_type text, p_limit integer, p_offset integer" },
  { name: "get_fast_organize_uncategorized", args: "p_user_id uuid, p_type text, p_limit integer, p_offset integer" },
  { name: "get_favorites_cursor_paginated", args: "p_user_id uuid, p_cursor timestamp with time zone DEFAULT NULL::timestamp with time zone, p_limit integer DEFAULT 20" },
  { name: "get_filtered_random_media", args: "limit_count integer, p_type text DEFAULT 'all'::text, p_category_id uuid DEFAULT NULL::uuid" },
  { name: "get_filtered_random_media", args: "limit_count integer, current_user_id uuid" },
  { name: "get_media_by_similar_hash", args: "p_hash text, p_threshold integer DEFAULT 5" },
  { name: "get_media_cursor_paginated", args: "p_cursor timestamp with time zone DEFAULT NULL::timestamp with time zone, p_limit integer DEFAULT 20, p_user_id uuid DEFAULT NULL::uuid, p_type text DEFAULT 'all'::text, p_category_id text DEFAULT 'all'::text, p_status text DEFAULT 'approved'::text" },
  { name: "get_media_library_v2", args: "p_page integer DEFAULT 0, p_limit integer DEFAULT 20, p_search text DEFAULT ''::text, p_status text DEFAULT 'all'::text, p_type text DEFAULT 'all'::text, p_category_id text DEFAULT 'all'::text, p_tag_id text DEFAULT 'all'::text" },
  { name: "get_media_with_thumbnails", args: "p_offset integer DEFAULT 0, p_limit integer DEFAULT 20, p_user_id uuid DEFAULT NULL::uuid, p_status text DEFAULT 'approved'::text" },
  { name: "get_optimized_media_items_v3", args: "p_user_id uuid DEFAULT NULL::uuid, p_type text DEFAULT 'all'::text, p_category_id text DEFAULT 'all'::text, p_tag_ids uuid[] DEFAULT NULL::uuid[], p_sort_by text DEFAULT 'latest'::text, p_limit integer DEFAULT 40, p_offset integer DEFAULT 0" },
  { name: "get_random_daily_gallery_images", args: "p_count integer, p_excluded_categories uuid[] DEFAULT '{}'::uuid[], p_excluded_tags uuid[] DEFAULT '{}'::uuid[]" },
  { name: "get_random_daily_gallery_images", args: "p_count integer" },
  { name: "get_random_daily_gallery_images_v2", args: "p_limit integer, p_offset integer, p_excluded_categories uuid[] DEFAULT ARRAY[]::uuid[], p_excluded_tags uuid[] DEFAULT ARRAY[]::uuid[]" },
  { name: "get_random_daily_gallery_images_v2", args: "p_limit integer DEFAULT 50, p_offset integer DEFAULT 0" },
  { name: "get_random_media", args: "limit_count integer" },
  { name: "get_random_media_items", args: "p_limit integer, p_user_id uuid DEFAULT NULL::uuid, p_type text DEFAULT 'all'::text, p_category_id text DEFAULT 'all'::text, p_tag_ids uuid[] DEFAULT NULL::uuid[]" },
  { name: "get_recommended_media", args: "p_user_id uuid DEFAULT NULL::uuid, p_limit integer DEFAULT 10, p_offset integer DEFAULT 0" },
  { name: "get_recommended_media_v2", args: "p_user_id uuid, p_limit integer, p_offset integer" },
  { name: "get_recommended_media_v2", args: "p_user_id uuid DEFAULT NULL::uuid, p_limit integer DEFAULT 10, p_offset integer DEFAULT 0, p_intensity integer DEFAULT 1" },
  { name: "get_recommended_media_v3", args: "p_user_id uuid, p_limit integer, p_offset integer, p_intensity double precision DEFAULT 1.0" },
  { name: "get_related_media", args: "p_media_id uuid, p_limit integer DEFAULT 10" },
  { name: "get_system_status", args: "" },
  { name: "get_tag_cloud_stats", args: "" },
  { name: "get_tag_management_stats", args: "" },
  { name: "get_tag_tree", args: "" },
  { name: "get_terminal_analytics", args: "" },
  { name: "get_top_disliked_media", args: "p_limit integer" },
  { name: "get_top_favorited_media", args: "limit_count integer" },
  { name: "get_unique_media_items", args: "p_limit integer, p_offset integer" },
  { name: "get_untagged_media", args: "p_page integer DEFAULT 0, p_limit integer DEFAULT 20, p_search text DEFAULT ''::text" },
  { name: "get_used_daily_gallery_images", args: "p_limit integer DEFAULT 50, p_offset integer DEFAULT 0" },
  { name: "get_used_daily_gallery_images", args: "p_limit integer, p_offset integer, p_search text DEFAULT NULL::text" },
  { name: "get_user_referral_tree", args: "" },
  { name: "get_visually_duplicate_media", args: "p_threshold integer DEFAULT 5" },
  { name: "get_visually_duplicate_media_v2", args: "similarity_threshold integer DEFAULT 5" },
  { name: "get_web_vitals_stats", args: "p_metric_name text DEFAULT NULL::text, p_days integer DEFAULT 7" },
  { name: "hamming_distance", args: "h1 text, h2 text" },
  { name: "handle_album_access_request_insertion", args: "" },
  { name: "handle_album_access_request_status_change", args: "" },
  { name: "handle_album_photo_count_change", args: "" },
  { name: "handle_album_photo_count_stmt_all", args: "" },
  { name: "handle_album_photo_count_stmt_delete", args: "" },
  { name: "handle_album_photo_count_stmt_upsert", args: "" },
  { name: "handle_auth_user_update", args: "" },
  { name: "handle_check_in_growth", args: "" },
  { name: "handle_comment_growth", args: "" },
  { name: "handle_daily_login_growth", args: "p_user_id uuid" },
  { name: "handle_favorite_count_change", args: "" },
  { name: "handle_favorite_growth", args: "" }
];

const dbFunctions = JSON.parse(process.argv[2]);

const results = userFunctions.map(uf => {
  const match = dbFunctions.find(df => df.function_name === uf.name && (df.arguments === uf.args || df.arguments.replace(/\s+/g, '') === uf.args.replace(/\s+/g, '')));
  if (match) {
    return { ...uf, status: "EXISTS" };
  }
  
  const nameMatch = dbFunctions.find(df => df.function_name === uf.name);
  if (nameMatch) {
    return { ...uf, status: "ARGS_MISMATCH", dbArgs: nameMatch.arguments };
  }
  
  return { ...uf, status: "MISSING" };
});

console.log(JSON.stringify(results, null, 2));
